-- Data Detective V4: Supabase schema
create table if not exists class_state (
  id integer primary key default 1,
  stage text not null default 'WAITING',
  round_no integer not null default 1,
  stage_started_at timestamptz default now(),
  updated_at timestamptz default now()
);

insert into class_state (id, stage, round_no)
values (1, 'WAITING', 1)
on conflict (id) do nothing;

create table if not exists pairs (
  id bigint generated by default as identity primary key,
  round_no integer not null,
  pair_no integer not null check (pair_no between 1 and 12),
  session_token text,
  joined_at timestamptz,
  think_answer text,
  think_submitted_at timestamptz,
  share_text text,
  share_submitted_at timestamptz,
  unique(round_no, pair_no)
);

-- Create the first 12 slots.
insert into pairs (round_no, pair_no)
select 1, g from generate_series(1,12) g
on conflict (round_no, pair_no) do nothing;

-- For a simple classroom app, the Streamlit server uses the Supabase key.
-- If you expose the project to the public, configure Supabase policies/RLS
-- according to your deployment/security requirements.
